# Site Settings
lang: en
title: Jcm236
tagline: Jcm236
email: johnchristi236@gmail.com
description: >
  This site is being renovated please visit later
baseurl: "/"
url: "jcm236.github.io"
permalink: pretty
#favicon: /path/to/favicon.png

#hide_share_buttons: true
#theme_color: '#eeeeee'
#fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr

paginate: 5
paginate_path: "/blog/page:num"



plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  
include: ['.well-known']

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "John Christi Monteiro"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: none

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
